CW11/Models/Enum/BrandEnum.cs
namespace CW11.Models.Enum
{
    public enum Brand
    {
        Samsung,
        Lenovo,
        Asus,
        huawei
    }
}

CW11/Models/Enum/CategoryEnum.cs
namespace CW11.Models.Enum
{
    public enum Category
    {
        Mobile,
        Laptop
    }
}

CW11/Models/ErrorViewModel.cs
namespace CW11.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CW11/Models/ProductModel.cs
using CW11.Models.Enum;

namespace CW11.Models
{
    public class ProductModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public Brand Brand { get; set; }
        public Category Category { get; set; }
        public DateTime AddedDate { get; set; }
    }
}

CW11/Controllers/HomeController.cs
using CW11.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CW11.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CW11/Controllers/StorageController.cs
using CW11.DataAccessLayer;
using CW11.Models;
using CW11.Models.Enum;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CW11.Controllers
{
    public class StorageController : Controller
    {
        ProductService _productService = new ProductService();

        public IActionResult Index()
        {
            var result = _productService.ReadAll();
            return View(result);
        }

        public IActionResult Create()
        {
            //var categoryList = Enum.GetValues(typeof(Category)).OfType<Category>()
            //    .Select(m => new { Text = m.ToString(), Value = (int)m }).ToList();
            return View(new ProductModel());
        }

        [HttpPost]
        public IActionResult Create(ProductModel product)
        {
            _productService.Create(product);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Update(int id)
        {
            //var categories = new List<Category>();
            //ViewBag.Categories = categories.Select(c => new SelectListItem{Text = }
            var product = _productService.Read(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Update(ProductModel product)
        {
            _productService.Update(product);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete(int id)
        {
            _productService.Delete(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

CW11/Views/Home/Index.cshtml
@using CW11.Models.Enum
@using CW11.DataAccessLayer
@model List<CW11.Models.ProductModel>
@{
    ViewData["Title"] = "CW11";
}
<a class="btn btn-primary" asp-controller="Storage" asp-action="Create">ایجاد محصول جدید</a>

<div class="card">
    <div class="row">
        <div class="col-6">
            <h3>Laptop Category</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Color</th>
                        <th>Model</th>
                        <th>Brand</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ProductRepository.Products)
                    {
                        if ((Convert.ToString(item.Category) == Convert.ToString(Category.Laptop)))
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Color</td>
                                <td>@item.Model</td>
                                <td>@item.Brand</td>
                                <td><a asp-route-id="@item.Id" asp-controller="Storage" asp-action="Update" class="btn btn-warning">ویرایش</a></td>
                                <td><a asp-route-id="@item.Id" asp-controller="Storage" asp-action="Delete" class="btn btn-danger">حذف</a></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <h3>Mobile Category</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Color</th>
                        <th>Model</th>
                        <th>Brand</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ProductRepository.Products)
                    {
                        if ((Convert.ToString(item.Category) == Convert.ToString(Category.Mobile)))
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Color</td>
                                <td>@item.Model</td>
                                <td>@item.Brand</td>
                                <td>
                                <td><a asp-route-id="@item.Id" asp-controller="Storage" asp-action="Update" class="btn btn-warning">ویرایش</a></td>
                                <td><a asp-route-id="@item.Id" asp-controller="Storage" asp-action="Delete" class="btn btn-danger">حذف</a></td>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

CW11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CW11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CW11.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CW11</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CW11 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CW11/Views/Storage/Create.cshtml
@using CW11.Models.Enum
@model ProductModel

<form method="post" asp-controller="Storage" asp-action="Create">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter Name">
    </div>
    <div class="mb-3">
        <label asp-for="Color" class="form-label">Color</label>
        <input asp-for="Color" type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter Color">
    </div>
    <div class="mb-3">
        <label asp-for="Model" class="form-label">Model</label>
        <input asp-for="Model" type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter Model">
    </div>
    <div class="mb-3">
        Category
        @{
            var categoryList = Enum.GetValues(typeof(Category)).OfType<Category>()
            .Select(m => new SelectListItem() { Text = m.ToString(), Value = m.ToString() }).ToList();
        }
        <select asp-for="Category" class="form-control" asp-items="@categoryList">
            <option disabled selected>
                دسته بندی کتگوری را انتخاب کنید
            </option>
        </select>
        @*@Html.DropDownList("EmpSex", new SelectList(categoryList, "Value", "Text", Model.Category))*@
    </div>
    <div class="mb-3">
        Brand
        @{
            var brandList = Enum.GetValues(typeof(Brand)).OfType<Brand>()
            .Select(m => new SelectListItem() { Text = m.ToString(), Value = m.ToString() }).ToList();
        }
        <select asp-for="Brand" class="form-control" asp-items="@brandList">
            <option disabled selected>
                دسته بندی برند را انتخاب کنید
            </option>
        </select>
        @* @{
        var brandList = Enum.GetValues(typeof(Brand)).OfType<Brand>()
        .Select(m => new { Text = m.ToString(), Value = (int)m }).ToList();
        }
        @Html.DropDownList("EmpSex", new SelectList(brandList, "Value", "Text", Model.Brand))*@
    </div>

    <button type="submit" class="btn btn-success">ثبت</button>
</form>

CW11/Views/Storage/Update.cshtml
@using CW11.Models.Enum
@model ProductModel

<form method="post">
    <div class="mb-3">
        <label asp-for="Id" class="form-label" style="display: none">Id</label>
        <input asp-for="Id" type="text" class="form-control" id="exampleInputEmail1" style="display: none">
    </div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" type="text" class="form-control" id="exampleInputEmail1">
    </div>
    <div class="mb-3">
        <label asp-for="Color" class="form-label">Color</label>
        <input asp-for="Color" type="text" class="form-control" id="exampleInputEmail1">
    </div>
    <div class="mb-3">
        <label asp-for="Model" class="form-label">Model</label>
        <input asp-for="Model" type="text" class="form-control" id="exampleInputEmail1">
    </div>
    <div class="mb-3">
        @*<label asp-for="Brand">Brand</label>
        <select asp-for="@Model.Brand" @*asp-items="@Html.EnumDropDownListFor(model => model.MyEnumProperty)"*@>
        @*</select>*@
        <label asp-for="Brand" class="form-label">Brand</label>
        <input asp-for="Brand" type="text" class="form-control" id="exampleInputEmail1">
    </div>
    <button asp-route-id="@Model.Id" asp-controller="Storage" asp-action="Update" type="submit" class="btn btn-primary">Submit</button>
</form>